### ISSUE TITLE
Scrapper Email Variable 

### ISSUE THREAD

**Issue by vakandi** [vakandi/email_scrapper#1]
Variable email contains html code,
Beautiful Soup doesn't trim the string well, need to fix it

**Comment by r3daaa** [comment]
fixed with this regex '[a-zA-Z0-9_.+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z0-9-.]+'

**Comment by vakandi** [comment]
And Fixed with loop in soup.find_all("a", href=True)**
